/** @format */
// todo : define actions type names

export const GET_STAFFS = "GET_STAFFS";
export const STAFFS_LOADING = "STAFF_LOADING";
export const STAFFS_LOADING_FAILED = "STAFFS_LOADING_FAILED";
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENTS_LOADING_FAILED = "DEPARTMENTS_LOADING_FAILED";
export const GET_SALARY = "GET_SALARY";
export const SALARY_LOADING = "SALARY_LOADING";
export const SALARY_LOADING_FAILED = "SALARY_LOADING_FAILED";
export const GET_STAFFS_OF_DEPARTMENT = "GET_STAFFS_OF_DEPARTMENT";
export const STAFFS_OF_DEPARTMENT_LOADING = "STAFFS_OF_DEPARTMENT_LOADING";
export const STAFFS_OF_DEPARTMENT_LOADING_FAILED = "STAFFS_OF_DEPARTMENT_LOADING_FAILED";
export const ADD_STAFF = "ADD_STAFF";
export const DELETE_STAFF = "DELETE_STAFF";
export const UPDATE_STAFF = "UPDATE_STAFF";
